const ORDER_STATUS = Object.freeze({
  PENDING: 'Pending',
  MEETUP_SCHEDULED: 'Meetup Scheduled',
  DELIVERED: 'Delivered',
  CANCELLED: 'Cancelled',
});

const ORDER_ALLOWED_TRANSITIONS = Object.freeze({
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.MEETUP_SCHEDULED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.MEETUP_SCHEDULED]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.DELIVERED]: [],
  [ORDER_STATUS.CANCELLED]: [],
});

const ORDER_STATUS_VALUES = Object.freeze(Object.values(ORDER_STATUS));

module.exports = {
  ORDER_STATUS,
  ORDER_ALLOWED_TRANSITIONS,
  ORDER_STATUS_VALUES,
};